site_name: Fumen
site_url: https://hbjpn.github.io/fumen/
repo_url: https://github.com/hbjpn/fumen/
site_description: "Markup language and rendering engine for music leadsheet creation with simple, easy and intuitive syntax, 
    supporting various types of compoents used in popular music's leadsheet such as chord symbols, rhythm slashes, rest marks, 
    repeat marks, reharsal marks, comments, lyrics."
nav:
    - Home: 'index.md'
    - Markdown:
      - Structure: 'structure.md'
      - Chords: 'chord.md'
      - Rests : 'rest.md'
      - 'Duration Indicator' : 'duration-indicator.md'
      - Repeat Signs : 'repeat-sign.md'
      - Time Signs : 'time-sign.md'
      - Text : 'text.md'
      - Variables : 'variable.md'
      - Transpose : 'transpose.md'

    - 'API':
      - 'Quick Start': 'api_quick_start.md'
      - 'Reference': 'api_reference.md'
theme:
    name: material
extra_css:
    - 'css/extra.css'
extra_javascript:
    - js/fumen.js
    - js/index.js
plugins:
    - mkdocs_fumen
site_dir: '../docs'
google_analytics:
  - UA-165626899-1
  - auto

