site_name: Fumen
nav:
    - Home: 'index.md'
    - Markdown:
      - Structure: 'structure.md'
      - Chords: 'chord.md'
      - Rests : 'rest.md'
      - 'Duration Indicator' : 'duration-indicator.md'
      - Repeat Signs : 'repeat-sign.md'
      - Time Signs : 'time-sign.md'
      - Text : 'text.md'
      - Variables : 'variable.md'
      - Transpose : 'transpose.md'

    - 'API':
      - 'API Reference': 'api.md'
theme:
    name: material
extra_css:
    - 'extra.css'
